### ISSUE TITLE
Missing class in sample (UsersViewBinding)

### ISSUE THREAD

**Issue by robisaks** [radzio/android-data-binding-recyclerview#4]
I managed around it, but your sample is missing a class.

net.droidlabs.mvvmdemo.databinding.UsersViewBinding

**Comment by radzio** [comment]
I'll check this.

**Comment by brol1dev** [comment]
I gotta comment on this. This isn't a bug. This is part of binding, check this link: https://developer.android.com/tools/data-binding/guide.html#binding_data.

When you build the project, it will generate the necessary binding classes. For this sample, it will generate the UsersViewBinding.
