### ISSUE TITLE
Question: recyclerview-binding

### ISSUE THREAD

**Issue by IgorGanapolsky** [radzio/android-data-binding-recyclerview#6]
Hi,
in your repo and your sample you rely on a library - <b>recyclerview-binding</b>.  However, in your README you don't mention it at all.  As a result, when I try to mimic your sample I am running into a wall because I am missing the classes that you have in <b>recyclerview-binding</b> library project.  Please advise on the significance of this library!

Thank you,
Igor

**Comment by radzio** [comment]
It should be more easy to understand it now. However I will update README soon.
