### ISSUE TITLE
I can not find the place where activityUsersRecycler set Adapter

### ISSUE THREAD

**Issue by maoruibin** [radzio/android-data-binding-recyclerview#8]
I read  this project, and have a try to find where activityUsersRecycler set BindingRecyclerViewAdapter , but fail , Maybe I am  not clear for DataBinding , please give me point .
thanks for you job !

**Comment by PhanVanLinh** [comment]
Set the id for `RecyclerView (android:id="@+id/activity_users_recycler")` will fix this error
